apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv
  namespace: ngsa
  labels:
    app.kubernetes.io/name: webv
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webv
  template:
    metadata:
      labels:
        app: webv
        version: beta
        deploy: 21-06-07-19-15-24
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/webvalidate:beta
          imagePullPolicy: Always
          args: 
          - --sleep 
          - "10" 
          - --run-loop 
          - --verbose 
          - --log-format 
          - Json 
          - --server 
          - https://aayodej1.aks-sb.com 
          - --files 
          - memory-benchmark.json
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: webv
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webv

