apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-webv
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-webv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-webv
  template:
    metadata:
      labels:
        app: ngsa-webv
        deploy: 21-05-14-19-15-24
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/webvalidate:beta
          imagePullPolicy: Always

          args: 
          - --sleep 1000 --run-loop --verbose --log-format Json --server https://${ASB_TEAM_NAME}.aks-sb.com --files memory-benchmark.json
          - --in-memory
          - --prometheus
          - --url-prefix

          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

      nodeSelector:
        agentpool: npuser01

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-webv
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-webv
