apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv
  namespace: ngsa
  labels:
    app.kubernetes.io/name: webv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webv
  template:
    metadata:
      labels:
        app: webv
    spec:
      containers:
        - name: app
          image: acraksdg6rerhg6uumi.azurecr.io/webvalidate:beta
          imagePullPolicy: Always

          args: 
          - --sleep 1000 
          - --run-loop 
          - --verbose 
          - --log-format Json 
          - --server https://${ASB_TEAM_NAME}.aks-sb.com 
          - --files memory-benchmark.json

    